# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35e9d5d84704f1891db0670e38a5f3673c5bffcce5f8fde89933fb190a452a38f420be3c84562a926fa937e3ebe3995d64da86d0e83207cac8fa48e34f1a6919

test:
  secret_key_base: 0816c51d680cc6604bdb4ce514ce552947c5c666ca82c6e829cd9e9a16a7f3227d7bdc2d737a979e8a37caee9413a9beabe6caf6cbec6a1593a1dfa520454629

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
